# Generated by Django 4.1.1 on 2022-12-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="subtitle",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
